# config/packages/nelmio_api_doc.yaml

nelmio_api_doc:
    documentation:
        info:
            title: 'Mon Projet Symfony'
            description: 'Documentation de mon API existante'
            version: '1.0.0'
    areas:
        path_patterns: # Ici, on dit de ne documenter que les URL commen√ßant par /api
            - ^/api
